language: generic
sudo: false
dist: xenial
jdk: openjdk8

env:
  global:
    BYOND_MAJOR="512"
    BYOND_MINOR="1488"

# ALL MAPS MUST BE PRESENT HERE
# IF THEY ARE NOT, YOUR BUILD WILL FAIL
matrix:
    include:
    - name: "DreamChecker"
      env: SPACEMAN_DMM_VERSION=suite-1.2
      cache:
        directories: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
      install:
        - ./scripts/install-spaceman-dmm.sh dreamchecker
      script:
        - ~/dreamchecker
    - name: "Code"
      env: TEST=CODE
    - name: "Map - Example"
      env: TEST=MAP MAP_PATH=example
    - name: "Map - Exodus"
      env: TEST=MAP MAP_PATH=exodus

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip
      - uchardet

script:
  - test/run-test.sh

after_success:
  - chmod +x ./send-to-discord.sh
  - ./send-to-discord.sh success $WEBHOOK_URL

after_failure:
  - chmod +x ./send-to-discord.sh
  - ./send-to-discord.sh failure $WEBHOOK_URL
